### ISSUE TITLE
Enabling `reuse_base_test` parameter fails the first time

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#118]
**Describe the bug**

Enabling to reuse base tests (`reuse_base_test=true`) fails if it is the first time you generate the test cases. The following exception is throwed:

```text
[tkltest|09:38:09.454] ERROR: Extending sequences and generating JUnit tests failed with return code 1: Exception in thread "main" java.io.IOException: /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services_RandoopTestGenerator_bb_test_sequences.json is not a valid file
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.<init>(TestSequenceExtender.java:242)
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.main(TestSequenceExtender.java:1856)
```

This feature should check if it is the first time, when there are not test generated, and continue without issues. Otherwise if I want to reuse test cases, then I need to check if it is the first time.

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- toml file configuration for generate cases:

```text
[generate.ctd_amplified]
    base_test_generator = "combined"
    augment_coverage = true
    no_ctd_coverage = false
    interaction_level = 1
    num_seq_executions = 10
    refactored_app_path_prefix = ""
    refactored_app_path_suffix = []
    reuse_base_tests = true
```

- The log file created by running the CLI with the `--verbose` and `--log-level INFO` options.

```shell
❯ tkltest --config-file ~/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml generate ctd-amplified
[tkltest|10:35:16.013] Loading config file /home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml
[tkltest|10:35:16.021] Computing coverage goals using CTD
* CTD interaction level: 1
* Total number of classes: 17
* Targeting 9 classes
* Skipping 8 classes with only private methods
* Created a total of 10 test combinations for 10 target methods of 9 target classes
[tkltest|10:35:16.885] Computing test plans with CTD took 0.86 seconds
[tkltest|10:35:16.885] Reusing existing basic block test sequences
[tkltest|10:35:16.885] Extending sequences to reach coverage goals and generating junit tests
* Read test plans for: 7 classes, 10 methods
[tkltest|10:35:17.583] ERROR: Extending sequences and generating JUnit tests failed with return code 1: Exception in thread "main" java.io.IOException: /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services_RandoopTestGenerator_bb_test_sequences.json is not a valid file
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.<init>(TestSequenceExtender.java:242)
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.main(TestSequenceExtender.java:1856)
```

- If the failure occurred for the `generate` command, please attach the following files if
  they were created during the failing run:
    - The CTD test plan JSON file (`simple-sample-services_ctd_models_and_test_plans.json`)

```json
{
  "models_and_test_plans" : {
    "monolithic" : {
      "com.acme.anvil.service.ProductCatalogBean" : {
        "setSessionContext(Ljavax/ejb/SessionContext;)V" : {
          "formatted_signature" : "void setSessionContext(javax.ejb.SessionContext)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "javax.ejb.SessionContext"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "javax.ejb.SessionContext"
          } ] ]
        }
      },
      "com.acme.anvil.vo.LogEvent" : {
        "setDate(Ljava/util/Date;)V" : {
          "formatted_signature" : "void setDate(java.util.Date)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "java.util.Date"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "java.util.Date"
          } ] ]
        },
        "<init>(Ljava/util/Date;Ljava/lang/String;)" : {
          "formatted_signature" : "com.acme.anvil.vo.LogEvent(java.util.Date,java.lang.String)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "java.util.Date"
            } ]
          }, {
            "attribute_name" : "attr_1",
            "values" : [ {
              "val_0" : "java.lang.String"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "java.util.Date"
          }, {
            "type" : "java.lang.String"
          } ] ]
        },
        "setMessage(Ljava/lang/String;)V" : {
          "formatted_signature" : "void setMessage(java.lang.String)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "java.lang.String"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "java.lang.String"
          } ] ]
        }
      },
      "com.acme.anvil.vo.Item" : {
        "setId(J)V" : {
          "formatted_signature" : "void setId(long)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "long"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "long"
          } ] ]
        }
      },
      "com.acme.anvil.service.jms.LogEventSubscriber" : {
        "onMessage(Ljavax/jms/Message;)V" : {
          "formatted_signature" : "void onMessage(javax.jms.Message)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "javax.jms.Message"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "javax.jms.Message"
          } ] ]
        }
      },
      "com.acme.anvil.listener.AnvilWebLifecycleListener" : {
        "contextInitialized(Ljavax/servlet/ServletContextEvent;)V" : {
          "formatted_signature" : "void contextInitialized(javax.servlet.ServletContextEvent)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "javax.servlet.ServletContextEvent"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "javax.servlet.ServletContextEvent"
          } ] ]
        },
        "contextDestroyed(Ljavax/servlet/ServletContextEvent;)V" : {
          "formatted_signature" : "void contextDestroyed(javax.servlet.ServletContextEvent)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "javax.servlet.ServletContextEvent"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "javax.servlet.ServletContextEvent"
          } ] ]
        }
      },
      "com.acme.anvil.service.ItemLookupBean" : {
        "lookupItem(J)Lcom/acme/anvil/vo/Item;" : {
          "formatted_signature" : "com.acme.anvil.vo.Item lookupItem(long)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "long"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "long"
          } ] ]
        }
      },
      "com.acme.anvil.service.jms.LogEventPublisher" : {
        "publishLogEvent(Lcom/acme/anvil/vo/LogEvent;)V" : {
          "formatted_signature" : "void publishLogEvent(com.acme.anvil.vo.LogEvent)",
          "attributes" : [ {
            "attribute_name" : "attr_0",
            "values" : [ {
              "val_0" : "com.acme.anvil.vo.LogEvent"
            } ]
          } ],
          "test_plan" : [ [ {
            "type" : "com.acme.anvil.vo.LogEvent"
          } ] ]
        }
      }
    }
  },
  "statistics" : {
    "total_classes" : 17,
    "target_classes" : 9,
    "non_public_classes" : 0,
    "classes_no_public_methods" : 8,
    "target_methods" : 10,
    "total_tests" : 10
  }
}
```

    - The building-block test sequences JSON files are not generated

**Environment information**

 - CLI version: 1.0.0 generated from the main branch
 - OS: 
```shell
❯ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
❯ uname -a
Linux redhat 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots**

NA

**Additional context**

If you generate the first time with the property disabled, it works. Then you could enable it and repeat the analysis, again it works

**Comment by rmarting** [comment]
Working successfully with the latest version in `main` branch.
