### ISSUE TITLE
`java_jdk_home` property is not working

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#119]
**Describe the bug**

Defining a path in `java_jdk_home` property to a local JDK8 such as:

```text
[general]
    java_jdk_home = "/usr/lib/jvm/java-1.8.0-openjdk"
```

does not work and the tool fails with the following exception:

```text
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/usr/lib/jvm/java-11-openjdk/lib/rt.jar' does not exist.
```

Also if the `JAVA_HOME` env variable is not used too

```shell
❯ export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
```

It seems that the tool is using the JDK from the path instead of both properties.

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- The toml file containing the configuration information used

```text
[general]
    app_name = "simple-sample-services"
    app_classpath_file = "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_classpath.txt"
    monolith_app_path = [
        "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/target/classes"
    ]
    java_jdk_home = "/usr/lib/jvm/java-1.8.0-openjdk"
    test_directory = ""
    reports_path = ""
    verbose = true
```

- The log file created by running the CLI with the `--verbose` and `--log-level INFO` options

```shell
❯ tkltest --config-file ~/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml generate ctd-amplified
[tkltest|10:54:00.155] Loading config file /home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml
[tkltest|10:54:00.161] Computing coverage goals using CTD
* CTD interaction level: 1
[tkltest|10:54:00.832] ERROR: Computing CTD coverage goals failed: Command 'java -Xmx2048m -cp ../lib/download/tackle-test-generator-core-1.0.0-SNAPSHOT.jar:../lib/acts_3.2.jar:../lib/download/commons-cli-1.4.jar:../lib/download/soot-4.1.0.jar:../lib/download/axml-2.0.0.jar:../lib/download/slf4j-api-1.7.5.jar:../lib/download/guava-29.0-jre.jar:../lib/download/failureaccess-1.0.1.jar:../lib/download/asm-7.1.jar:../lib/download/asm-analysis-7.1.jar:../lib/download/asm-commons-7.1.jar:../lib/download/asm-tree-7.1.jar:../lib/download/asm-utils-7.1.jar:../lib/download/heros-1.2.0.jar:../lib/download/httpcore-4.4.6.jar:../lib/download/httpclient-4.5.13.jar:../lib/download/jackson-databind-2.12.5.jar:../lib/download/jackson-core-2.12.5.jar:../lib/download/jackson-annotations-2.12.5.jar org.konveyor.tackle.testgen.model.CTDTestPlanGenerator  -app simple-sample-services -pt /home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/target/classes -clpt tkltest_classpath.txt -ic 1' returned non-zero exit status 1.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/usr/lib/jvm/java-11-openjdk/lib/rt.jar' does not exist.
        at soot.SourceLocator.getClassSourceType(SourceLocator.java:312)
        at soot.SourceLocator.lookupInClassPath(SourceLocator.java:615)
        at soot.asm.AsmClassProvider.find(AsmClassProvider.java:39)
        at soot.SourceLocator.getClassSource(SourceLocator.java:187)
        at soot.Scene.tryLoadClass(Scene.java:1028)
        at soot.Scene.loadBasicClasses(Scene.java:1742)
        at soot.Scene.loadNecessaryClasses(Scene.java:1843)
        at org.konveyor.tackle.testgen.util.Utils.initSootClasses(Utils.java:168)
        at org.konveyor.tackle.testgen.model.RapidTypeAnalysis.performAnalysis(RapidTypeAnalysis.java:80)
        at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.<init>(CTDTestPlanGenerator.java:139)
        at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.main(CTDTestPlanGenerator.java:1130)
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/usr/lib/jvm/java-11-openjdk/lib/rt.jar' does not exist.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:525)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:102)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:237)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2279)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
        at soot.SourceLocator.getClassSourceType(SourceLocator.java:310)
        ... 10 more
Caused by: java.lang.Exception: Error: The path '/usr/lib/jvm/java-11-openjdk/lib/rt.jar' does not exist.
        at soot.SourceLocator$1.load(SourceLocator.java:73)
        at soot.SourceLocator$1.load(SourceLocator.java:68)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        ... 16 more
```

- JDK runtime defined in path, but `JAVA_HOME` changed:

```shell
❯ java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
❯ export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
```

**Environment information**

 - CLI version: 1.0.0 build from main branch
 - OS:
```shell
❯ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
❯ uname -a
Linux redhat 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots**

NA

**Additional context**

If `PATH` variable is updated to use the new `JAVA_HOME` property, then it is working successfully:

```shell
❯ echo $JAVA_HOME 
/usr/lib/jvm/java-1.8.0-openjdk
❯ PATH="$JAVA_HOME/bin:$PATH"
❯ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

**Comment by sinha108** [comment]
Fixed and merged

**Comment by rmarting** [comment]
Latest version in `main` branch is working successfully. Now I can define which jdk version instead of to change my local setup.

```text
[general]
    java_jdk_home = "/usr/lib/jvm/java-1.8.0-openjdk"
```
