### ISSUE TITLE
Generating test with `augment_coverage=true' fails

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#123]
**Describe the bug**

Generating test cases enabling the property `augment_coverage` fails with the following exception:

```text
subprocess.CalledProcessError: Command 'ant -f simple-sample-services-ctd-amplified-tests/build.xml merge-coverage-report' returned non-zero exit status 127.
```

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- The toml file containing the configuration information used

```text
[general]
    app_name = "simple-sample-services"
    app_classpath_file = "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_classpath.txt"
    monolith_app_path = [
        "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/target/classes"
    ]
    java_jdk_home = ""
    test_directory = ""
    reports_path = ""
    verbose = true

[generate]
    jee_support = true
    no_diff_assertions = false
    partitions_file = ""
    target_class_list = []
    excluded_class_list = []
    time_limit = 10
    app_build_config_file = "pom.xml"
    app_build_settings_file = ""

[generate.ctd_amplified]
    base_test_generator = "combined"
    augment_coverage = true
    no_ctd_coverage = false
    interaction_level = 1
    num_seq_executions = 10
    refactored_app_path_prefix = ""
    refactored_app_path_suffix = []
    reuse_base_tests = true

[generate.evosuite]
    criterion = [ "BRANCH",]

[generate.randoop]
    no_error_revealing_tests = false

[execute]
    app_packages = [ "com.acme.anvil.*" ]
    build_type = "maven"
    create_build_file = false
    code_coverage = true
    online_instrumentation = false
    test_class = ""
```

- The log file created by running the CLI with the `--verbose` and `--log-level INFO` options

```shell
❯ tkltest --config-file ~/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml generate ctd-amplified
[tkltest|12:30:37.487] Loading config file /home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml
[tkltest|12:30:37.495] Computing coverage goals using CTD
* CTD interaction level: 1
* Total number of classes: 17
* Targeting 9 classes
* Skipping 8 classes with only private methods
* Created a total of 10 test combinations for 10 target methods of 9 target classes
[tkltest|12:30:38.399] Computing test plans with CTD took 0.9 seconds
[tkltest|12:30:38.399] Reusing existing basic block test sequences
[tkltest|12:30:38.399] Extending sequences to reach coverage goals and generating junit tests
* Read test plans for: 7 classes, 10 methods
* Read 1530 base test sequences
* Starting sequence parsing
*   Full:1521  Part:0  Skip:4  Excp:5
* Class sequence pool: 8 classes, 8 sequences
* Method sequence pool: 5 methods, 101 sequences
* Parsed initial test sequences for 7 classes; total parsed sequences (full+partial): 1521
* Generating extended test sequences
* Partition: monolithic
* Processing class com.acme.anvil.service.ProductCatalogBean
*   1 methods .
*   generated 1 test sequences
*   -- class test-plan coverage rate: 100.00% (1/1)
*   wrote test class file for com.acme.anvil.service.ProductCatalogBean to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 1 test methods
* Processing class com.acme.anvil.vo.LogEvent
*   3 methods ...
*   generated 3 test sequences
*   -- class test-plan coverage rate: 100.00% (3/3)
*   wrote test class file for com.acme.anvil.vo.LogEvent to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 3 test methods
* Processing class com.acme.anvil.vo.Item
*   1 methods .
*   generated 1 test sequences
*   -- class test-plan coverage rate: 100.00% (1/1)
*   wrote test class file for com.acme.anvil.vo.Item to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 1 test methods
* Processing class com.acme.anvil.service.jms.LogEventSubscriber
*   1 methods .
*   generated 0 test sequences
*   -- class test-plan coverage rate: 0.00% (0/1)
*   wrote test class file for com.acme.anvil.service.jms.LogEventSubscriber to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 0 test methods
* Processing class com.acme.anvil.listener.AnvilWebLifecycleListener
*   2 methods ..
*   generated 0 test sequences
*   -- class test-plan coverage rate: 0.00% (0/2)
*   wrote test class file for com.acme.anvil.listener.AnvilWebLifecycleListener to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 0 test methods
* Processing class com.acme.anvil.service.ItemLookupBean
*   1 methods .
*   generated 0 test sequences
*   -- class test-plan coverage rate: 0.00% (0/1)
*   wrote test class file for com.acme.anvil.service.ItemLookupBean to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 0 test methods
* Processing class com.acme.anvil.service.jms.LogEventPublisher
*   1 methods .
*   generated 0 test sequences
*   -- class test-plan coverage rate: 0.00% (0/1)
*   wrote test class file for com.acme.anvil.service.jms.LogEventPublisher to "simple-sample-services-ctd-amplified-tests-tkltest-tmp/monolithic" with 0 test methods
* === total CTD test-plan coverage rate: 50.00% (5/10)
* created 7 test classes in total, with 5 test methods and 4 assertions
* wrote summary file for generation of CTD-amplified tests (JSON)
* wrote CTD test-plan coverage report (JSON)
[tkltest|12:31:00.710] JUnit tests are saved in /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests-tkltest-tmp
[tkltest|12:31:00.711] Extending test sequences and writing junit tests took 22.31 seconds
[tkltest|12:31:00.712] Test plan coverage report is saved in /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-tkltest-reports/ctd-report/test-plan-summary.html
/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-evosuite-tests
[tkltest|12:31:00.784] Generated Ant build file /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests/simple-sample-services-ctd-amplified-tests/build.xml
[tkltest|12:31:00.784] Generated Maven build file /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests/simple-sample-services-ctd-amplified-tests/pom.xml
[tkltest|12:31:00.784] Generated Gradle build file /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests/simple-sample-services-ctd-amplified-tests/build.gradle
[tkltest|12:31:00.784] Performing coverage-driven test-suite augmentation and optimization
Traceback (most recent call last):
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/venv/bin/tkltest", line 33, in <module>
    sys.exit(load_entry_point('tkltest', 'console_scripts', 'tkltest')())
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/tkltest.py", line 206, in main
    generate.process_generate_command(args, tkltest_config)
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/generate.py", line 50, in process_generate_command
    generate_ctd_amplified_tests(config)
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/generate.py", line 217, in generate_ctd_amplified_tests
    augment_with_code_coverage(config=config, ant_build_file=ant_build_file,
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/augment.py", line 47, in augment_with_code_coverage
    test_class_augment_pool, base_test_coverage, ctd_test_dir_bak = __compute_base_and_augment_test_suites(
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/augment.py", line 127, in __compute_base_and_augment_test_suites
    __compute_coverage_efficiency(test_dir=ctd_test_dir, ant_build_file=ant_build_file, report_dir=report_dir,
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/augment.py", line 182, in __compute_coverage_efficiency
    test_coverage = coverage_util.get_coverage_for_test_suite(ant_build_file=ant_build_file,
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/util/coverage_util.py", line 51, in get_coverage_for_test_suite
    command_util.run_command("ant -f {} merge-coverage-report".format(ant_build_file), verbose=False)
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/util/command_util.py", line 40, in run_command
    subprocess.run(command, shell=True, check=True, stdout=subprocess.DEVNULL,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ant -f simple-sample-services-ctd-amplified-tests/build.xml merge-coverage-report' returned non-zero exit status 127.
```

- Source code of the application available [here](https://github.com/windup/migration-sample-app). Generating the test cases for simple-sample-services module.

- `tlktest_classpath.txt` file from `app_classpath_file` option

```text
/home/rmarting/.m2/repository/org/jboss/windup/test/apps/weblogic/proprietary-stub/1.0.0-SNAPSHOT/proprietary-stub-1.0.0-SNAPSHOT.jar
/home/rmarting/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
/home/rmarting/.m2/repository/javax/ejb/ejb-api/3.0/ejb-api-3.0.jar
/home/rmarting/.m2/repository/org/jboss/ejb3/jboss-ejb3-ext-api/2.1.0/jboss-ejb3-ext-api-2.1.0.jar
/home/rmarting/.m2/repository/javax/javaee-api/7.0/javaee-api-7.0.jar
/home/rmarting/.m2/repository/com/sun/mail/javax.mail/1.5.0/javax.mail-1.5.0.jar
/home/rmarting/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
/home/rmarting/.m2/repository/javaee/javaee-api/5/javaee-api-5.jar
/home/rmarting/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar
```

**Environment information**

 - CLI version 1.0.0 from main branch
 - OS:
```shell
❯ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
❯ uname -a
Linux redhat 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots**

NA

**Additional context**

NA

**Comment by rachelt44** [comment]
@rmarting can you also please upload the content of the folder 'simple-sample-services-evosuite-tests'? thank you!

**Comment by rmarting** [comment]
@rachelt44 here! 
[simple-sample-services-evosuite-tests.zip](https://github.com/konveyor/tackle-test-generator-cli/files/7768950/simple-sample-services-evosuite-tests.zip)

**Comment by rachelt44** [comment]
@rmarting running on the latest `main` branch with the evosuite tests you sent me, augmentation works for me and is able to increase instruction coverage from 12% to 61.8%. Can you please check the latest code?

```
[tkltest|15:25:30.818] Summary of coverage-based augmentation of "simple-sample-services-ctd-amplified-tests": test_classes_added=5, instruction_cov_gain=180, branch_cov_gain=1
[tkltest|15:25:30.819] Final test-suite coverage rate: instruction=223/361(61.8%), branch=1/4(25.0%), line=70/106(66.0%), method=33/38(86.8%)
```

**Comment by rmarting** [comment]
Yes, same results!!!

**Comment by rachelt44** [comment]
Awosome!
