### ISSUE TITLE
Exception while generating testcases for a module

### ISSUE THREAD

**Issue by UshnishChowdhury** [konveyor/tackle-test-generator-cli#264]
**The following exception was thrown:**
```
[tkltest|12:47:55.687] Loading config file ./gat-was-config/tkltest_config.toml
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.jee_support
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.partitions_file
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.add_assertions
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.app_build_type
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.ctd_amplified.refactored_app_path_prefix
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.ctd_amplified.refactored_app_path_suffix
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.ctd_amplified.ctd_coverage
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: generate.randoop.no_error_revealing_tests
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: execute.build_type
[tkltest|12:47:55.690] Warning: Unsupported flag in toml file: execute.online_instrumentation
[tkltest|12:49:09.799] Generating tests for app gat-was using config file ./gat-was-config/tkltest_config.toml.
[tkltest|12:49:09.923] Computing coverage goals using CTD
[tkltest|12:49:59.796] Computing test plans with CTD took 49.87 seconds
[tkltest|12:49:59.796] Generating basic block test sequences using CombinedTestGenerator
[tkltest|12:49:59.796] Test generator output will be written to gat-was_CombinedTestGenerator_output.log
[tkltest|17:43:18.952] Generating basic block test sequences with CombinedTestGenerator took 17599.16 seconds
[tkltest|17:43:18.954] Extending sequences to reach coverage goals and generating junit tests
[tkltest|18:04:17.810] ERROR: Extending sequences and generating JUnit tests failed with return code 1: Exception in thread "main" java.lang.ClassCastException: randoop.types.NonParameterizedType cannot be cast to randoop.types.InstantiatedType
        at org.konveyor.tackle.testgen.core.extender.JavaCollectionTypes.getMapTypeInstantiationInfo(JavaCollectionTypes.java:314)
        at org.konveyor.tackle.testgen.core.extender.ConstructorSequenceGenerator.createConstructorParameter(ConstructorSequenceGenerator.java:255)
        at org.konveyor.tackle.testgen.core.extender.ConstructorSequenceGenerator.createSequenceForConstructor(ConstructorSequenceGenerator.java:155)
        at org.konveyor.tackle.testgen.core.extender.ConstructorSequenceGenerator.createConstructorSequence(ConstructorSequenceGenerator.java:100)
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.augmentClassSequencePool(TestSequenceExtender.java:1787)
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.<init>(TestSequenceExtender.java:271)
        at org.konveyor.tackle.testgen.core.extender.TestSequenceExtender.main(TestSequenceExtender.java:2004)
```

I have attached the toml file
[tkltest_config.txt](https://github.com/konveyor/tackle-test-generator-cli/files/8814527/tkltest_config.txt)
.

**Comment by rachelt44** [comment]
Fixed and merged via PR: https://github.com/konveyor/tackle-test-generator-core/pull/150
