### ISSUE TITLE
TackleTest is failing during augmentation when the ctd-generated test suite is of size zero

### ISSUE THREAD

**Issue by rachelt44** [konveyor/tackle-test-generator-cli#313]
**Describe the bug**

Run TackleTest unit on the following app: https://github.com/shashirajraja/onlinebookstore/

With Java 8

Toml file:

[tkltest_config.zip](https://github.com/konveyor/tackle-test-generator-cli/files/9775848/tkltest_config.zip)

```
[tkltest|13:43:46.831] Coverage information for CTD-guided tests: instruction=0/0(0.0%), branch=0/0(0.0%), line=0/0(0.0%), method=0/0(0.0%)
                                                 coverage_efficiency=0 (0 test methods)
Traceback (most recent call last):
  File "C:\MyStuff\MyStuffWork\ConTest\Modernization\Workspace\tackle-test-generator-cli\venv\Scripts\tkltest-unit-script.py", line 33, in <module>
    sys.exit(load_entry_point('tkltest', 'console_scripts', 'tkltest-unit')())
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\tkltest_unit.py", line 76, in main
    __process_command(args, config)
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\tkltest_unit.py", line 108, in __process_command
    generate.process_generate_command(args, config)
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\generate\unit\generate.py", line 55, in process_generate_command
    generate_ctd_amplified_tests(config, output_dir)
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\generate\unit\generate.py", line 246, in generate_ctd_amplified_tests
    has_coverage = augment_with_code_coverage(config=config, build_file=build_file, build_type=build_type,
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\generate\unit\augment.py", line 70, in augment_with_code_coverage
    __compute_base_and_augmenting_tests_coverage(
  File "c:\mystuff\mystuffwork\contest\modernization\workspace\tackle-test-generator-cli\tkltest\generate\unit\augment.py", line 190, in __compute_base_and_augmenting_tests_coverage
    for dir in [dir for dir in os.listdir(ctd_test_dir) if os.path.isdir(dir) and dir != 'build' and dir != 'target']:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'onlinebookstore-ctd-amplified-tests'
```
**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- The toml file containing the configuration information used
- The log file created by running the CLI with the `--verbose` and `--log-level INFO` options
- If possible, a zip file containing the application classes, and the file specified as
  `app_classpath_file` option in the toml file together with the library dependencies listed
  in the file
- If the failure occurred for the `generate` command, please attach the following files if
  they were created during the failing run:
    - The CTD test plan JSON file (`<app-name>_ctd_models_and_test_plans.json`)
    - The building-block test sequences JSON files (`<app-name>_EvoSuiteTestGenerator_bb_test_sequences.json`
      and/or `<app-name>_RandoopTestGenerator_bb_test_sequences.json`)
- If the failure occurred for the `execute` command, please attach the zip file of the directory
  containing the generated test JUnit test cases

**Environment information**

 - CLI version
 - OS: [e.g., Linux, macOS, Windows]

**Screenshots**

**Additional context**

**Comment by rachelt44** [comment]
Fixed and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/314
