### ISSUE TITLE
NoSuchFileException: /modules/modules

### ISSUE THREAD

**Issue by gkephart-apptricity** [konveyor/tackle-test-generator-cli#328]
I'm running:
tkltest-unit --verbose generate ctd-amplified

and am getting "java.nio.file.NoSuchFileException: /modules/modules"

Stack trace:
       at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
        at soot.asm.AsmJava9ClassProvider.find(AsmJava9ClassProvider.java:50)
        at soot.SourceLocator.getClassSource(SourceLocator.java:187)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:231)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:182)
        at soot.SootResolver.resolveClass(SootResolver.java:141)
        at soot.Scene.tryLoadClass(Scene.java:1040)
        at soot.Scene.loadBasicClasses(Scene.java:1742)
        at soot.Scene.loadNecessaryClasses(Scene.java:1843)
        at org.konveyor.tackle.testgen.util.Utils.initSootClasses(Utils.java:183)
        at org.konveyor.tackle.testgen.model.RapidTypeAnalysis.performAnalysis(RapidTypeAnalysis.java:87)
        at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.<init>(CTDTestPlanGenerator.java:147)
        at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.main(CTDTestPlanGenerator.java:1160)
j
[tkltest_config.toml.zip](https://github.com/konveyor/tackle-test-generator-cli/files/10902579/tkltest_config.toml.zip)

**Comment by ngovanminh3232** [comment]
You shoulde show example code .toml in test forlder in github

**Comment by rachelt44** [comment]
@gkephart-apptricity what version of Python are you using?
