### ISSUE TITLE
Installation Guide Doesn't Work For Me

### ISSUE THREAD

**Issue by heidenthal-gtisoft** [konveyor/tackle-test-generator-cli#339]
Hello,

I work on a legacy software project with low code coverage via unit tests.  I am eager to increase the coverage using your tool as I have read many good things about EvoSuite and randoop.  However, I have spent almost a day configuring tackle-test to have it still not work.  Any help you can give, is greatly appreciated.

### Description
I completed all the instructions in https://github.com/konveyor/tackle-test-generator-cli/blob/main/doc/installation.md#installing-prerequisites.  This was challenging due to needing Python 3.9.  I finally found that the Windows Store was the best way to get it

Then, I followed the instructions in https://github.com/konveyor/tackle-test-generator-cli/blob/main/doc/installation.md#installing-the-tackletest-cli.  Everything worked except the command tkltest-ui --help which output the following:

### Output of tkltest-ui --help
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Downloads\tackle-test-generator-cli\venv\Scripts\tkltest-ui.exe\__main__.py", line 4, in <module>
  File "D:\Downloads\tackle-test-generator-cli\tkltest\ui\tkltest_ui.py", line 26, in <module>
    from tkltest.ui.generate import generate
  File "D:\Downloads\tackle-test-generator-cli\tkltest\ui\generate\generate.py", line 30, in <module>
    from tkltest.ui.generate import generate_selenium
  File "D:\Downloads\tackle-test-generator-cli\tkltest\ui\generate\generate_selenium.py", line 29, in <module>
    from tkltest.ui.generate.heuristic_labels import HeuristicLabel
  File "D:\Downloads\tackle-test-generator-cli\tkltest\ui\generate\heuristic_labels.py", line 4, in <module>
    import nltk
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\nltk\__init__.py", line 137, in <module>
    from nltk.text import *
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\nltk\text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\nltk\tokenize\__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\nltk\tokenize\casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

### Description (continued)
Thinking I wouldn't need the ui since I am working with the CLI only, no docker, I pressed on to the User Guide.

I created a TOML configuration file using https://github.com/konveyor/tackle-test-generator-cli/blob/main/test/data/splitNjoin/tkltest_config.toml as suggested.  NOTE: I tried both txt and toml extensions when executing the generate command, with no difference.

This is the command I executed:
tkltest-unit -cf .\todd_config.txt generate ctd-amplified

By the way, it is very odd to have to include a sub-command for generate when it is already in the configuration file.

### Output of tkltest-unit -cf .\todd_config.txt generate ctd-amplified
The output of that command was:
[tkltest|13:22:07.342] Loading config file .\todd_config.toml
Traceback (most recent call last):
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Downloads\tackle-test-generator-cli\venv\Scripts\tkltest-unit.exe\__main__.py", line 7, in <module>
  File "D:\Downloads\tackle-test-generator-cli\tkltest\unit\tkltest_unit.py", line 64, in main
    tkltest_config = load_configuration(args, 'unit')
  File "D:\Downloads\tackle-test-generator-cli\tkltest\tkltest.py", line 177, in load_configuration
    tkltest_config = config_util.load_config(args=args, test_level=test_level)
  File "D:\Downloads\tackle-test-generator-cli\tkltest\util\config_util.py", line 61, in load_config
    toml_config = toml.load(args.config_file)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Reserved escape sequence used (line 16 column 1 char 481)

### Description (continued)
I am not Python literate, but am a skilled developer, so I can learn.  I am running Windows 10.0.19044 on a Lenovo laptop with the following specifications:
* 12th Gen Intel(R) Core(TM) i7-12800HX, 2000 Mhz, 16 Core(s), 24 Logical Processor(s)
* 64 GB of installed RAM 
* 2TB drive with plenty of space.

I very much would like to be able to present tackle-test to the company as a possible solution to the lack of unit tests.

I look forward to hearing from you,
Todd

[todd_config.txt](https://github.com/konveyor/tackle-test-generator-cli/files/12316138/todd_config.txt)

**Comment by rachelt44** [comment]
@heidenthal-gtisoft you need to replace all backslashes with double backslashes in your toml file, e.g.:
app_build_files = ["D:\\workspace\\development\\GUI\\adopted\\GitEmber\\build.gradle"]

**Comment by heidenthal-gtisoft** [comment]
@rachelt44, thanks for the feedback.  I updated my toml file to have double backslashes and rexecuted 

tkltest-unit -cf .\todd_config.txt generate ctd-amplified

This is the result:

[tkltest|09:30:11.240] Loading config file .\todd_config.txt
Traceback (most recent call last):
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Downloads\tackle-test-generator-cli\venv\Scripts\tkltest-unit.exe\__main__.py", line 7, in <module>
  File "D:\Downloads\tackle-test-generator-cli\tkltest\unit\tkltest_unit.py", line 64, in main
    tkltest_config = load_configuration(args, 'unit')
  File "D:\Downloads\tackle-test-generator-cli\tkltest\tkltest.py", line 177, in load_configuration
    tkltest_config = config_util.load_config(args=args, test_level=test_level)
  File "D:\Downloads\tackle-test-generator-cli\tkltest\util\config_util.py", line 61, in load_config
    toml_config = toml.load(args.config_file)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "D:\Downloads\tackle-test-generator-cli\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 29 column 1 char 792)

[todd_config.txt](https://github.com/konveyor/tackle-test-generator-cli/files/12322505/todd_config.txt)

**Comment by rachelt44** [comment]
@heidenthal-gtisoft please add double quotes to the `DEBUG` value of `log_level`, i.e.,:

log_level = \"DEBUG\"

**Comment by heidenthal-gtisoft** [comment]
@rachelt44 Thank you very much for your help.  I am now to the point that I must debug my project configuration for the issues that tackle tests is reporting.
