### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#60]
**Describe the bug**
Got the below error while running on MdhDataLoader: Project shared in IBM Git

Same error occured in product-dataload-service in pdl module.

Exception in thread "main" java.io.IOException: org.konveyor.tackle.testgen.core.EvoSuiteTestGenerator: java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long

        at org.konveyor.tackle.testgen.core.TestSequenceInitializer.createInitialTests(TestSequenceInitializer.java:243)        at org.konveyor.tackle.testgen.core.TestSequenceInitializer.main(TestSequenceInitializer.java:533)

**Attachments**

**Environment information**

 - OS: Windows

**Screenshots**
** MDHDataLoader Screenshot**
![image](https://user-images.githubusercontent.com/22675218/129484321-49505007-3b79-488e-bdad-76592fd57be0.png)

** product-dataload-service - PDL Screenshot**
![image](https://user-images.githubusercontent.com/22675218/129484434-73f71053-7497-490d-8da4-61ae288807e1.png)

**Additional context**

**Comment by rachelt44** [comment]
We'll reduce the size of the command for EvoSuite by targeting classes instead of individual methods.
