### ISSUE TITLE
Error executing command without arguments

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#89]
**Describe the bug**

Executing `tkltest` command without any argument fails with the following exception:

```shell
❯ tkltest 
Traceback (most recent call last):
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/venv/bin/tkltest", line 33, in <module>
    sys.exit(load_entry_point('tkltest', 'console_scripts', 'tkltest')())
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/tkltest.py", line 185, in main
    logging_util.tkltest_status('Loading config file {}'.format(args.config_file.name))
AttributeError: 'NoneType' object has no attribute 'name'
```

The command should check if the arguments list to show an usage message if the arguments are not compliant.

**Attachments**

**Environment information**

 - CLI version:

```shell
❯ tkltest -v
0.0.1
```

 - OS: 
 
```shell
❯ uname -a
Linux redhat 5.14.9-200.fc34.x86_64 #1 SMP Thu Sep 30 11:55:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
❯ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
```

**Comment by sinha108** [comment]
Fixed and merged
